/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_jp_snjp_x264demo_view_YUVPlayer */

#ifndef _Included_co_jp_snjp_x264demo_view_YUVPlayer
#define _Included_co_jp_snjp_x264demo_view_YUVPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_jp_snjp_x264demo_view_YUVPlayer
 * Method:    Open
 * Signature: (Ljava/lang/String;Ljava/lang/Object;II)V
 */
JNIEXPORT void JNICALL Java_co_jp_snjp_x264demo_view_YUVPlayer_Open
  (JNIEnv *, jobject, jstring, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
